{
 "title": "SecureTenant Platform",
 "tags": [ "securetenant" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests by tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (tenant_id) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "Security failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(security_denied_total[5m]))",
     "legendFormat": "denied"
    }
   ]
  },
  {
   "title": "API latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Orders created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(orders_created_total[5m]))",
     "legendFormat": "created"
    }
   ]
  },
  {
   "title": "Payments created / settled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(payments_created_total[5m]))",
     "legendFormat": "created"
    },
    {
     "expr": "sum(increase(payments_settled_total[5m]))",
     "legendFormat": "settled"
    }
   ]
  },
  {
   "title": "Payments failed / retried",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(payments_failed_total[5m]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(payments_retried_total[5m]))",
     "legendFormat": "retried"
    }
   ]
  }
 ]
}